import * as crypto from "crypto";

/**
 * Sign a createValidator response using HMAC-SHA256.
 *
 * The signature authenticates the response to the caller, proving that
 * the deposit data was generated by the holder of the API key.
 *
 * Message format: `{requestId}:{timestamp}:{depositDataRoot}`
 *
 * @param requestId - The x-request-id echoed from the request
 * @param timestamp - Unix timestamp (seconds) when the response was generated
 * @param depositDataRoot - SSZ Merkle root from the deposit data (0x-prefixed)
 * @param apiKey - The shared API key used as the HMAC secret
 * @returns Hex-encoded HMAC-SHA256 signature (64 hex chars)
 */
export function signResponse(
  requestId: string,
  timestamp: string,
  depositDataRoot: string,
  apiKey: string,
): string {
  const message = `${requestId}:${timestamp}:${depositDataRoot}`;
  return crypto.createHmac("sha256", apiKey).update(message).digest("hex");
}

/**
 * Verify an HMAC-SHA256 response signature using timing-safe comparison.
 *
 * @returns true if the signature is valid
 */
export function verifySignature(
  requestId: string,
  timestamp: string,
  depositDataRoot: string,
  apiKey: string,
  signature: string,
): boolean {
  const expected = signResponse(requestId, timestamp, depositDataRoot, apiKey);

  if (expected.length !== signature.length) {
    return false;
  }

  return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature));
}
